runtime: python312
entrypoint: uvicorn main:app  --host 0.0.0.0 --port 8080
instance_class: F1

env_variables:
  BUCKET_NAME: "effdelbackendapis.appspot.com"

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8


handlers:
# Matches product_requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
